### ISSUE TITLE
RBD Cache support

### ISSUE THREAD

**Issue by Jazz9** [ceph/ceph-iscsi-cli#100]
Hello

I have just started using this in Centos 7.5 and was wondering if RBD cache is supported? I have tried the normal ceph.conf settings but can't see any improvement.

**Comment by dillaman** [comment]
@Jazz9 The RBD cache is currently explicitly disabled by tcmu-runner (https://github.com/open-iscsi/tcmu-runner/blob/c85ccdcfb7f4b17926eda1df89e592f5fd9ac5d4/rbd.c#L441)

**Comment by Jazz9** [comment]
I guess that makes sense when you consider failover / active - active.

Thanks for your help.
