### ISSUE TITLE
iSCSI login failed due to authorization failure

### ISSUE THREAD

**Issue by platoxie** [ceph/ceph-iscsi-cli#13]
login iqn.2003-01.com.redhat.iscsi-gw:ceph-igw failed
I don't understand gwcli set chap under client name.
1. does iscsiadm need to specify the name of the client when it login to target?
2.if the client name have some rules，such astarget-name:client-name？

Login result:
**iscsiadm -m node -T iqn.2003-01.com.redhat.iscsi-gw:ceph-igw -l**
Logging in to [iface: default, target: iqn.2003-01.com.redhat.iscsi-gw:ceph-igw, portal: 172.16.121.131,3260] (multiple)
Logging in to [iface: default, target: iqn.2003-01.com.redhat.iscsi-gw:ceph-igw, portal: 172.16.121.130,3260] (multiple)
iscsiadm: Could not login to [iface: default, target: iqn.2003-01.com.redhat.iscsi-gw:ceph-igw, portal: 172.16.121.131,3260].
iscsiadm: initiator reported error (24 - **iSCSI login failed due to authorization failure**)
iscsiadm: Could not login to [iface: default, target: iqn.2003-01.com.redhat.iscsi-gw:ceph-igw, portal: 172.16.121.130,3260].
iscsiadm: initiator reported error (24 - iSCSI login failed due to authorization failure)
iscsiadm: Could not log into all portals

Prepare for login:
vi /etc/iscsi/iscsid.conf
node.session.auth.authmethod = CHAP
**node.session.auth.username = consumer
node.session.auth.password = 012345678912**

restart iscsid

/> ls
o- / .............................................................. [...]
  o- clusters ............................................. [Clusters: 1]
  | o- c1 ................................................. [HEALTH_WARN]
  |   o- pools ............................................... [Pools: 1]
  |   | o- rbd ................... [(x3), Commit: 384M/6G (6%), Used: 3K]
  |   o- topology ..................................... [OSDs: 1,MONs: 1]
  o- disks ............................................. [384M, Disks: 3]
  | o- rbd.disk_1 ....................................... [disk_1 (128M)]
  | o- rbd.disk_2 ....................................... [disk_2 (128M)]
  | o- rbd.disk_3 ....................................... [disk_3 (128M)]
  o- iscsi-target .......................................... [Targets: 1]
    o- iqn.2003-01.com.redhat.iscsi-gw:ceph-igw ........... [Gateways: 2]
      o- gateways ................................. [Up: 2/2, Portals: 2]
      | o- node0 .................................. [172.16.121.130 (UP)]
      | o- node1 .................................. [172.16.121.131 (UP)]
      o- host-groups ....................................... [Groups : 0]
      o- hosts ............................................... [Hosts: 3]
        o- iqn.1994-05.com.redhat:rh7-client . [Auth: None, Disks: 0(0b)]
        o- iqn.1994-05.com.redhat:xx ....... [Auth: CHAP, Disks: 1(128M)]
        | o- lun 0 ..................... [rbd.disk_1(128M), Owner: node1]
        o- iqn.2003-01.com.redhat.iscsi-gw:nike  [Auth: CHAP, Disks: 1(128M)]
          o- lun 0 ..................... [rbd.disk_2(128M), Owner: node0]

rbd-target-api.log:
- (_get_rbd_config) config object contains '{
    "clients": {
        **"iqn.1994-05.com.redhat:rh7-client":** {
            "auth": {
                "chap": ""
            },
            "created": "2017/08/28 06:08:53",
            "group_name": "",
            "luns": {},
            "updated": "2017/08/28 06:08:53"
        },
        **"iqn.1994-05.com.redhat:xx":** {
            "auth": {
                **"chap": "consumer/012345678912"**
            },
            "created": "2017/08/29 03:05:00",
            "group_name": "",
            "luns": {
                "rbd.disk_1": {
                    "lun_id": 0
                }
            },
            "updated": "2017/08/29 06:20:45"
        },
        **"iqn.2003-01.com.redhat.iscsi-gw:nike":** {
            "auth": {
                **"chap": "consumer/012345678912"**
            },
            "created": "2017/08/29 07:07:28",
            "group_name": "",
            "luns": {
                "rbd.disk_2": {
                    "lun_id": 0
                }
            },
            "updated": "2017/08/29 07:11:57"
        }
    },
    "created": "2017/08/28 03:26:42",
    "disks": {
        "rbd.disk_1": {
            "created": "2017/08/29 02:41:52",
            "image": "disk_1",
            "owner": "node1",
            "pool": "rbd",
            "pool_id": 1,
            "updated": "2017/08/29 02:41:52",
            "wwn": "95c0d3a9-96cf-4158-9341-88020e2cc8d7"
        },
        "rbd.disk_2": {
            "created": "2017/08/29 03:02:49",
            "image": "disk_2",
            "owner": "node0",
            "pool": "rbd",
            "pool_id": 1,
            "updated": "2017/08/29 03:02:49",
            "wwn": "8383bdfa-1e94-4a94-ae59-c33a0dd7a737"
        },
        "rbd.disk_3": {
            "created": "2017/08/29 03:03:51",
            "image": "disk_3",
            "owner": "node1",
            "pool": "rbd",
            "pool_id": 1,
            "updated": "2017/08/29 03:03:51",
            "wwn": "d80cc287-4b16-408b-932a-b5ede4e5bc96"
        }
    },
    "epoch": 20,
    "gateways": {
        "created": "2017/08/28 03:31:58",
        "ip_list": [
            "172.16.121.131",
            "172.16.121.130"
        ],
        "iqn": "iqn.2003-01.com.redhat.iscsi-gw:ceph-igw",
        "node0": {
            "active_luns": 1,
            "created": "2017/08/28 04:00:44",
            "gateway_ip_list": [
                "172.16.121.131",
                "172.16.121.130"
            ],
            "inactive_portal_ips": [
                "172.16.121.131"
            ],
            "iqn": "iqn.2003-01.com.redhat.iscsi-gw:ceph-igw",
            "portal_ip_address": "172.16.121.130",
            "tpgs": 2,
            "updated": "2017/08/29 03:02:49"
        },
        "node1": {
            "active_luns": 2,
            "created": "2017/08/28 03:33:26",
            "gateway_ip_list": [
                "172.16.121.131",
                "172.16.121.130"
            ],
            "inactive_portal_ips": [
                "172.16.121.130"
            ],
            "iqn": "iqn.2003-01.com.redhat.iscsi-gw:ceph-igw",
            "portal_ip_address": "172.16.121.131",
            "tpgs": 2,
            "updated": "2017/08/29 03:03:51"
        }
    },
    "groups": {},
    "updated": "2017/08/29 07:11:57",
    "version": 3
}'

**Comment by mikechristie** [comment]
For 1 and 2, I'm not sure what you mean but the initiator name is on the initiator side is in /etc/iscsi/initiatorname.iscsi. During the login process it's sends the target this name so yeah it has to match what you set on the target side.

**Comment by platoxie** [comment]
@mikechristie 
gwcli can create many clients，each client have single auth. so if the initiator loging to target, which auth would ititiator use?

 iscsi-target .......................................... [Targets: 1]
    o- iqn.2003-01.com.redhat.iscsi-gw:ceph-igw ........... [Gateways: 2]
      o- gateways ................................. [Up: 2/2, Portals: 2]
      | o- node0 .................................. [172.16.121.130 (UP)]
      | o- node1 .................................. [172.16.121.131 (UP)]
      o- host-groups ....................................... [Groups : 0]
      o- hosts ............................................... [Hosts: 3]
        o- **iqn.1994-05.com.redhat:rh7-client** . [**Auth: None**, Disks: 0(0b)]
        o- **iqn.1994-05.com.redhat:xx** ....... [**Auth: CHAP**, Disks: 1(128M)]
        | o- lun 0 ..................... [rbd.disk_1(128M), Owner: node1]
        o- **iqn.2003-01.com.redhat.iscsi-gw:nike**  [**Auth: CHAP**, Disks: 1(12

**Comment by pcuzner** [comment]
each client defined in gwcli can have 1-WAY auth (CHAP) defined. On the initiator side, the client's iqn (/etc/iscsi/initiatorname.iscsi) must match the definition in gwcli, and the username and password defined in the clients iscsid.conf must match the gwcli chap settings (node.session..)
e.g. 
in iscsid.conf
node.session.auth.username = myuser
node.session.auth.password = mypassword1234

and then in gwcli check auth with the info command
```
o- hosts ..................................................................................... [Hosts: 1]
  o- iqn.1994-05.com.redhat:rh7-client ....................................... [Auth: CHAP, Disks: 0(0b)]
/iscsi-target...ceph-gw/hosts> iqn.1994-05.com.redhat:rh7-client/ info 
Client Iqn .. iqn.1994-05.com.redhat:rh7-client
Logged In  .. 
Auth
- chap .. myuser/mypassword1234
Group Name .. 
Luns       .. UNDEFINED
```

**Comment by platoxie** [comment]
@mikechristie @pcuzner : I define the client name same with target name( iqn.2003-01.com.redhat.iscsi-gw:ceph-igw).  initiator login successfully.
Thanks a lot!

/iscsi-target...eph-igw/hosts> iqn.2003-01.com.redhat.iscsi-gw:ceph-igw/ info
Client Iqn .. iqn.2003-01.com.redhat.iscsi-gw:ceph-igw
Logged In  .. LOGGED_IN
Auth
- chap .. consumer/012345678912
Group Name .. 
Luns
- rbd.disk_1 .. lun_id=0
- rbd.disk_3 .. lun_id=1
