### ISSUE TITLE
gwcli fails on creating disk

### ISSUE THREAD

**Issue by deckardbsd** [ceph/ceph-iscsi-cli#150]
I have installed two gateways on centos 7.5 with patched kernel:  4.15.0-ceph-g1c778f43da52 and tcmu-runner: tcmu-runner-1.3.0-0.2rc4.el7.x86_64
I'm trying to create a disk using gwcli, but it fails with the following error msg:
`Failed : disk create/update failed on iscsi-gw1. Unhandled exception: __init__() got an unexpected keyword argument 'control'`

**Comment by dillaman** [comment]
You need to update your python-rtslib-fb packages -- they are out-of-date.

**Comment by deckardbsd** [comment]
I have: python2-rtslib-2.1.fb67-3.fc28.noarch

**Comment by deckardbsd** [comment]
I do have: python2-rtslib 2.1.fb67-3.fc28

**Comment by dillaman** [comment]
You need this [1] so if you are getting an error about the missing ```control``` keyword, you don't have the updated version. 1.fb67-3.fc28 is not the most up-to-date version -- you need at least fb68.

[1] https://github.com/open-iscsi/rtslib-fb/blob/master/rtslib/tcm.py#L811

**Comment by deckardbsd** [comment]
Thanks, it works !
