### ISSUE TITLE
gwcli KeyError: 'groups'

### ISSUE THREAD

**Issue by gzsy2000** [ceph/ceph-iscsi-cli#153]
Why do I exit gwcli directly after I configure iqn?
Then keep reminding
[root@ceph-target-1 bin]# gwcli
KeyError: 'groups'

**Comment by gzsy2000** [comment]
You can manually delete everything and re-enter gwcli
command:
Rados -p rbd rm gateway.conf

**Comment by mikechristie** [comment]
Did you find a solution to your issue?

If not send the /var/log/rbd-target-api/rbd-target-api.log and output of gwlci with debugging on:

gwcli -d

when it crashes.

And then also send the version info.

**Comment by gzsy2000** [comment]
谢谢你的关注
我已经解决了，原因是当时rbd的pool down 了
然后执行命令
Rados -p rbd rm gateway.conf
问题解决

**Comment by gzsy2000** [comment]
Thank you for your attention
I have solved it because the rbd's pool was down.
Then execute the command
Rados -p rbd rm gateway.conf
problem solved

**Comment by hamidreza-hosseini** [comment]
I have the same issue, when I wan to add second gateway it jumps out out gwcli by this error:
"KeyError: 'targets'"
My issue details:
```
https://github.com/ceph/ceph-iscsi-config/issues/104
```
