### ISSUE TITLE
rbd-target-gw  AttributeError: 'Config' object has no attribute 'config'

### ISSUE THREAD

**Issue by xadhoom76** [ceph/ceph-iscsi-cli#28]
Hi, when I try to start the rbd-target-api and gw we receive this error.
We are on CentOS 7 3.10.0-693.2.2.el7 and luminous ceph
thanks

**Comment by pcuzner** [comment]
@xadhoom76 Not sure when you took the code - but there was a bug introduced which caused this error. Now fixed on master.

**Comment by xadhoom76** [comment]
I take the master from here
 File "/usr/lib/python2.7/site-packages/ceph_iscsi_config-2.3-py2.7.egg/EGG-INFO/scripts/rbd-target-g
Sep 28 10:51:55 pve4.ocstwin.local rbd-target-gw[11012]: File "/usr/lib/python2.7/site-packages/ceph_iscsi_config-2.3-py2.7.egg/EGG-INFO/scripts/rbd-target-g
Sep 28 10:51:55 pve4.ocstwin.local rbd-target-gw[11012]: File "build/bdist.linux-x86_64/egg/ceph_iscsi_config/lio.py", line 58, in drop_target
Sep 28 10:51:55 pve4.ocstwin.local rbd-target-gw[11012]: AttributeError: 'Config' object has no attribute 'config'
Sep 28 10:51:55 pve4.ocstwin.local rbd-target-gw[11012]: Original exception was:
Sep 28 10:51:55 pve4.ocstwin.local rbd-target-gw[11012]: Traceback (most recent call last):
Sep 28 10:51:55 pve4.ocstwin.local rbd-target-gw[11012]: File "/usr/bin/rbd-target-gw", line 5, in <module>
Sep 28 10:51:55 pve4.ocstwin.local rbd-target-gw[11012]: pkg_resources.run_script('ceph-iscsi-config==2.3', 'rbd-target-gw')
Sep 28 10:51:55 pve4.ocstwin.local rbd-target-gw[11012]: File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 540, in run_script
Sep 28 10:51:55 pve4.ocstwin.local rbd-target-gw[11012]: self.require(requires)[0].run_script(script_name, ns)
Sep 28 10:51:55 pve4.ocstwin.local rbd-target-gw[11012]: File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 1462, in run_script
Sep 28 10:51:55 pve4.ocstwin.local rbd-target-gw[11012]: exec_(script_code, namespace, namespace)
Sep 28 10:51:55 pve4.ocstwin.local rbd-target-gw[11012]: File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 41, in exec_
Sep 28 10:51:55 pve4.ocstwin.local rbd-target-gw[11012]: exec("""exec code in globs, locs""")
Sep 28 10:51:55 pve4.ocstwin.local rbd-target-gw[11012]: File "<string>", line 1, in <module>
Sep 28 10:51:55 pve4.ocstwin.local rbd-target-gw[11012]: File "/usr/lib/python2.7/site-packages/ceph_iscsi_config-2.3-py2.7.egg/EGG-INFO/scripts/rbd-target-g
Sep 28 10:51:55 pve4.ocstwin.local rbd-target-gw[11012]: File "/usr/lib/python2.7/site-packages/ceph_iscsi_config-2.3-py2.7.egg/EGG-INFO/scripts/rbd-target-g
Sep 28 10:51:55 pve4.ocstwin.local rbd-target-gw[11012]: File "/usr/lib/python2.7/site-packages/ceph_iscsi_config-2.3-py2.7.egg/EGG-INFO/scripts/rbd-target-g
Sep 28 10:51:55 pve4.ocstwin.local rbd-target-gw[11012]: File "build/bdist.linux-x86_64/egg/ceph_iscsi_config/lio.py", line 58, in drop_target
Sep 28 10:51:55 pve4.ocstwin.local rbd-target-gw[11012]: AttributeError: 'Config' object has no attribute 'config'
Sep 28 10:51:55 pve4.ocstwin.local rbd-target-gw[11012]: Removing Ceph iSCSI configuration from LIO
Sep 28 10:51:55 pve4.ocstwin.local rbd-target-gw[11012]: Removing iSCSI target from LIO
Sep 28 10:51:55 pve4.ocstwin.local rbd-target-gw[11012]: Removing iSCSI target from LIO
Sep 28 10:51:55 pve4.ocstwin.local systemd[1]: rbd-target-gw.service: main process exited, code=exited, status=1/FAILURE
Sep 28 10:51:55 pve4.ocstwin.local systemd[1]: Unit rbd-target-gw.service entered failed state.
Sep 28 10:51:55 pve4.ocstwin.local systemd[1]: rbd-target-gw.service failed.
Sep 28 10:51:55 pve4.ocstwin.local systemd[1]: rbd-target-gw.service holdoff time over, scheduling restart.
Sep 28 10:51:55 pve4.ocstwin.local systemd[1]: start request repeated too quickly for rbd-target-gw.service
Sep 28 10:51:55 pve4.ocstwin.local systemd[1]: Failed to start Setup system to export rbd images through LIO.
-- Subject: Unit rbd-target-gw.service has failed

Any ideas ? thanks

**Comment by xadhoom76** [comment]
I also can see this 
Sep 28 11:18:17 pve4.ocstwin.local systemd[1]: Dependency failed for Ceph iscsi target configuration API.
-- Subject: Unit rbd-target-api.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit rbd-target-api.service has failed.
--
-- The result is dependency.
Sep 28 11:18:17 pve4.ocstwin.local systemd[1]: Job rbd-target-api.service/start failed with result 'dependency'.
Sep 28 11:18:17 pve4.ocstwin.local systemd[1]: rbd-target-gw.service failed.
Sep 28 11:18:17 pve4.ocstwin.local polkitd[645]: Unregistered Authentication Agent for unix-process:11567:15556986 (system bus name :1.886, object path /org/

**Comment by mikechristie** [comment]
@xadhoom76 

Could you repull, so we can make sure you have the current code which we think has a fix for this?

**Comment by Jorpilo** [comment]
I've just pull it from master and I am getting the same error

[adm@osd0 rbd-target-gw.service.d]$ sudo rbd-target-gw
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/ceph_iscsi_config-2.3-py2.7.egg/EGG-INFO/scripts/rbd-target-gw", line 33, in exception_handler

  File "/usr/lib/python2.7/site-packages/ceph_iscsi_config-2.3-py2.7.egg/EGG-INFO/scripts/rbd-target-gw", line 85, in clearconfig

  File "build/bdist.linux-x86_64/egg/ceph_iscsi_config/lio.py", line 58, in drop_target
AttributeError: 'Config' object has no attribute 'config'

Original exception was:
Traceback (most recent call last):
  File "/bin/rbd-target-gw", line 5, in <module>
    pkg_resources.run_script('ceph-iscsi-config==2.3', 'rbd-target-gw')
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 540, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 1462, in run_script
    exec_(script_code, namespace, namespace)
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 41, in exec_
    exec("""exec code in globs, locs""")
  File "<string>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/ceph_iscsi_config-2.3-py2.7.egg/EGG-INFO/scripts/rbd-target-gw", line 466, in <module>

  File "/usr/lib/python2.7/site-packages/ceph_iscsi_config-2.3-py2.7.egg/EGG-INFO/scripts/rbd-target-gw", line 214, in halt

  File "/usr/lib/python2.7/site-packages/ceph_iscsi_config-2.3-py2.7.egg/EGG-INFO/scripts/rbd-target-gw", line 85, in clearconfig

  File "build/bdist.linux-x86_64/egg/ceph_iscsi_config/lio.py", line 58, in drop_target
AttributeError: 'Config' object has no attribute 'config'

**Comment by Jorpilo** [comment]
Ok I think I solved myself.

you need to create a file in /etc/ceph/ called iscsi-gateway.cfg with the initial configuration as described in the guide:

http://docs.ceph.com/docs/master/rbd/iscsi-target-cli/
