### ISSUE TITLE
Exception if "api_secure" mismatch between gateways

### ISSUE THREAD

**Issue by dillaman** [ceph/ceph-iscsi-cli#29]
Likely also occurs if the public/private keys differ between hosts as well.

> Traceback (most recent call last):
>   File "/usr/bin/gwcli", line 187, in <module>
>     main()
>   File "/usr/bin/gwcli", line 119, in main
>     shell.run_interactive()
>   File "/usr/lib/python2.7/site-packages/configshell_fb/shell.py", line 905, in run_interactive
>     self._cli_loop()
>   File "/usr/lib/python2.7/site-packages/configshell_fb/shell.py", line 734, in _cli_loop
>     self.run_cmdline(cmdline)
>   File "/usr/lib/python2.7/site-packages/configshell_fb/shell.py", line 848, in run_cmdline
>     self._execute_command(path, command, pparams, kparams)
>   File "/usr/lib/python2.7/site-packages/configshell_fb/shell.py", line 823, in _execute_command
>     result = target.execute_command(command, pparams, kparams)
>   File "/usr/lib/python2.7/site-packages/configshell_fb/node.py", line 1406, in execute_command
>     return method(*pparams, **kparams)
>   File "/usr/lib/python2.7/site-packages/gwcli/gateway.py", line 519, in ui_command_create
>     msg = api.response.json()['message']
>   File "/usr/lib/python2.7/site-packages/requests/models.py", line 802, in json
>     return json.loads(self.text, **kwargs)
>   File "/usr/lib64/python2.7/json/__init__.py", line 338, in loads
>     return _default_decoder.decode(s)
>   File "/usr/lib64/python2.7/json/decoder.py", line 366, in decode
>     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
>   File "/usr/lib64/python2.7/json/decoder.py", line 384, in raw_decode
>     raise ValueError("No JSON object could be decoded")
> ValueError: No JSON object could be decoded
>

**Comment by pcuzner** [comment]
should be resolved by #31
