### ISSUE TITLE
How to find the sessions connected by initiators

### ISSUE THREAD

**Issue by vatelzh** [ceph/ceph-iscsi-cli#45]
I can't find the initiator sessions from gwcli command

**Comment by vatelzh** [comment]
targetcli command can do this, closing it.

**Comment by pcuzner** [comment]
gwcli lists the hosts, and if the host is logged in the entry shows LOGGED-IN
e.g.
```  
      o- hosts ............................................ [Hosts: 2]  
        o- iqn.1998-01.com.vmware:esx65-1-4d3e6170  [LOGGED-IN, Auth: CHAP, Disks: 2(300G)]  
        | o- lun 0 ....... [ssd-pool.datastore1(200G), Owner: rh7-gw2]  
        | o- lun 1 ............ [rbd.iso_images(100G), Owner: rh7-gw1]  
```  
Is this what you're after?

**Comment by vatelzh** [comment]
I looked through targetcli code, both gwcli and targetcli is using rtslib to wrap to UI command. Do we need  to list sessions in gwcli?

**Comment by pcuzner** [comment]
Client connection state is provided in gwcli - the idea being to provide a shell to support common worflows so the admin doesn't have to have 10 sessions open :) Case in point is the ceph cluster informaton.

targetcli is OK to check state...but you shouldn't use it to make changes to the local gateway.

**Comment by vatelzh** [comment]
@pcuzner not exactly,  your example is only list the sessions owner, I this people may want to know initiator ip/hostname info.
In targetcli:
targetcli sessions detail
alias: 	sid: 8 type: Normal session-state: LOGGED_IN
    name: iqn.2017-11.test:vmware (NOT AUTHENTICATED)
    mapped-lun: 0 backstore: user/rbd.vmware0 mode: rw
    mapped-lun: 1 backstore: user/rbd.vmware1 mode: rw
    address: **192.168.0.11** (TCP)  cid: 0 connection-state: LOGGED_IN

**Comment by pcuzner** [comment]
ok, that's what the info command is for
```  
/iscsi-target...ceph-gw/hosts> iqn.1998-01.com.vmware:esx65-1-4d3e6170/ info 
Client Iqn .. iqn.1998-01.com.vmware:esx65-1-4d3e6170
Logged In  .. LOGGED_IN
Auth
- chap .. iqn.1998-01.com.vmware:esx65-1-4d3e6170/mysupersecret
Group Name .. esx
Luns
- rbd.iso_images      .. lun_id=1
- ssd-pool.datastore1 .. lun_id=0
```

**Comment by vatelzh** [comment]
ok, still no initiator ip/hostname informations list

**Comment by pcuzner** [comment]
true - perhaps that could be added to the info output along with alias?

**Comment by vatelzh** [comment]
That will be great :)

**Comment by pcuzner** [comment]
@vatelzh 

What about this;
```  
/iscsi-target...ceph-gw/hosts> iqn.1998-01.com.vmware:esx65-1-4d3e6170/ info
Client Iqn .. iqn.1998-01.com.vmware:esx65-1-4d3e6170
Ip Address .. 10.90.90.31
Alias      .. esx65-1
Logged In  .. LOGGED_IN
Auth
- chap .. iqn.1998-01.com.vmware:esx65-1-4d3e6170/mysupersecret
Group Name .. esx
Luns
- rbd.iso_images      .. lun_id=1
- ssd-pool.datastore1 .. lun_id=0
```

**Comment by vatelzh** [comment]
Perfect, 10.90.90.31 is the initiator ip address, right?

**Comment by pcuzner** [comment]
yes. The connections are stored in a list, so if you get several ip's the IP address shown will be comma separated.

**Comment by pcuzner** [comment]
patch in #49

**Comment by vatelzh** [comment]
👍
