### ISSUE TITLE
rbd-target-gw failed to start

### ISSUE THREAD

**Issue by vatelzh** [ceph/ceph-iscsi-cli#50]
Traceback (most recent call last):
  File "/usr/bin/rbd-target-gw", line 468, in <module>
    main()
  File "/usr/bin/rbd-target-gw", line 419, in main
    apply_config()
  File "/usr/bin/rbd-target-gw", line 388, in apply_config
    gateway = define_gateway()
  File "/usr/bin/rbd-target-gw", line 259, in define_gateway
    gateway.manage('target')
  File "/usr/lib/python2.7/site-packages/ceph_iscsi_config/gateway.py", line 426, in manage
    self.create_target()
  File "/usr/lib/python2.7/site-packages/ceph_iscsi_config/gateway.py", line 230, in create_target
    for ip in self.gateway_ip_list:
AttributeError: 'GWTarget' object has no attribute 'gateway_ip_list'

I gdb to the code, and found that there's **inconsistent** between gateways, 
In another two gateways:
1 gateway is inaccessible - updates will be disabled
/iscsi-target...aaaa/gateways> ls
o- gateways ..................................................................... [Up: 2/3, Portals: 3]
  o- node1 ...................................................................... [192.168.15.201 (UP)]
  o- node2 ................................................................. [192.168.15.202 (UNKNOWN)]      <-----node2 is here
  o- node3 ...................................................................... [192.168.15.203 (UP)]

and in node2, I start gateway
> /usr/lib/python2.7/site-packages/ceph_iscsi_config/gateway.py(49)__init__()
-> matching_ip = set(gateway_ip_list).intersection(ipv4_addresses())
(Pdb) l
 44  	            import pdb
 45  	            pdb.set_trace()
 46  	            # if the ip list provided doesn't match any ip of this host, abort
 47  	            # the assumption here is that we'll only have one matching ip in
 48  	            # the list!
 49  ->	            matching_ip = set(gateway_ip_list).intersection(ipv4_addresses())
 50  	            if len(list(matching_ip)) == 0:
 51  	                self.error = True
 52  	                self.error_msg = ("gateway IP addresses provided do not match"
 53  	                                  " any ip on this host")
 54  	                return
(Pdb) p set(gateway_ip_list).intersection(ipv4_addresses())
set([]) 
(Pdb) p gateway_ip_list
[u'192.168.15.201', u'192.168.15.203']          <------node2 is not in the list
(Pdb) p ipv4_addresses()
['192.168.15.202']

I checkout the gateway.conf from rbd, and node2 is not in the gateway_ip_list...

How should I get my environment normal? Should we add an API to delete unavaliable gateways?

**Comment by vatelzh** [comment]
or any steps to reinitialize my environment? :(

**Comment by pcuzner** [comment]
If you don't care about the config you have you can wipe it by
1. shutdown the rbd-target-gw daemon on each gateway
2. check with targetcli that the LIO config is empty on each gateway
3. delete the config object (rados -p rbd rm gateway.conf)
4. start the rbd-target-gw daemons on the gateways that you want to use (this will create an empty config object)
5. check/start the rbd-target-api daemon
6. use gwcli to create the target and gateways

This is the quickest way I can think of

**Comment by vatelzh** [comment]
@pcuzner thanks for your quickly reply, that works.  
Could we add delete command for gateways? If gateway is down permanently, how to handle this scenario?

**Comment by pcuzner** [comment]
In order to delete a gateway, we also have to rebalance the LUNs. So the first thing we need to add is a rebalance feature, then we can look at gateway delete.

**Comment by vatelzh** [comment]
Got it, is this feature in the roadmap?
