### ISSUE TITLE
Any disk operation needs at least 2 gateways to be present

### ISSUE THREAD

**Issue by gelato** [ceph/ceph-iscsi-cli#54]
Please elaborate on this statement. Why 2 gateways and what 2nd gateway i should add?

**Comment by pcuzner** [comment]
2 gateways purely from a HA perspective. You can add another gateway on another OSD host or separate server - either would be fine. Basically when you present an rbd image to an iscsi client, the client's multi-pathing layer will provide failover, so if a gateway is rebooted or fails access to data will continue

**Comment by gelato** [comment]
And why presence of 2 gateways is mandatory? Let's assume i want only 1 gateway, in code i saw that this option is configurable, but how?

**Comment by mikechristie** [comment]
If you only want to use 1 gateway then you do not need all this stuff. You can just use targetcli-fb directly like normal with iblock and krbd.

**Comment by pcuzner** [comment]
Closing as issue appears inactive - please reopen if required
