### ISSUE TITLE
vSphere Client: can not find iscsi target by using dynamic discovery

### ISSUE THREAD

**Issue by vatelzh** [ceph/ceph-iscsi-cli#57]
steps:
1, Create a host using gwcli named iqn.2016-04.com.test.sn1
2, Config iscsi adapter, rename the wwn to  iqn.2016-04.com.test.sn1
3, Fill the chap and IP(192.168.0.20) using dynaimc discovery and click 'ok', no device, no path found...
4, If using static discovery, device and path can be found again.

**Comment by mikechristie** [comment]
We do not support CHAP during discovery. The discovery CHAP settings on the ESX side should be set so it does not try to use it.

**Comment by vatelzh** [comment]
@mikechristie  it works, thank you very much.
