### ISSUE TITLE
Trouble Adding Second Gateway Server to GWCLI

### ISSUE THREAD

**Issue by squarejester** [ceph/ceph-iscsi-cli#59]
Please help as this is stopping me cold.

Having a problem adding a second gateway server. Both the first and second gateways are on dedicated servers on Centos 7. 

The 10.2.51.0/24 subnet is the primary subnet (ceph public network) and is routable.
The 10.2.41.0/24 subnet is only used by iSCSI initiators to connect to the gateways and is not routable. 

I created the first gateway as cephrgw01 with an ip address of 10.2.51.41. That same first gateway server has a secondary ip address of 10.2.41.41 (seen in the error below).

I created the second gateway as cephrgw02 with an ip address of 10.2.51.43. That same second gateway server has a secondary ip address of 10.2.41.43 (was originally seen in the error message but disappeared once I rebooted the server). Rebooting the first server did not remove this error.

I initially ran gwcli on cephrgw01 and was able to create the gateway cephrgw01 without any issues. I then tried to add a disk but got the message about needing a second gateway, so I tried to add a second gateway.

In the first server when I try to create the second gateway after running gwcli as root I get this....

/iscsi-target...test/gateways> create skipchecks=true cephrgw02 10.2.51.43
CMD: ../gateways/ create cephrgw02 10.2.51.43 nosync=False skipchecks=true
OS version/package checks have been bypassed
Adding gateway, sync'ing 0 disk(s) and 0 client(s)
**Failed : Gateway creation failed, gateway(s) unavailable:10.2.41.41(UNKNOWN state)**
/iscsi-target...test/gateways>

On the second gateway I get this when I try to run gwcli I only get this...

[root@cephrgw02 ~]# gwcli
KeyError: 403
[root@cephrgw02 ~]#

When I run gwcli -d I get this......

Adding ceph cluster 'ceph' to the UI
Fetching ceph osd information
Querying ceph for state information
Refreshing disk information from the config object
Refreshing gateway & client information
- checking iSCSI/API ports on cephrgw01
Traceback (most recent call last):
  File "/usr/bin/gwcli", line 187, in <module>
    main()
  File "/usr/bin/gwcli", line 99, in main
    root_node.refresh()
  File "/usr/lib/python2.7/site-packages/gwcli/gateway.py", line 78, in refresh
    self.target.refresh()
  File "/usr/lib/python2.7/site-packages/gwcli/gateway.py", line 341, in refresh
    tgt.gateway_group.load(self.gateway_group)
  File "/usr/lib/python2.7/site-packages/gwcli/gateway.py", line 406, in load
    Gateway(self, gateway_name, gateway_group[gateway_name])
  File "/usr/lib/python2.7/site-packages/gwcli/gateway.py", line 604, in __init__
    self.refresh()
  File "/usr/lib/python2.7/site-packages/gwcli/gateway.py", line 620, in refresh
    self._get_state()
  File "/usr/lib/python2.7/site-packages/gwcli/gateway.py", line 649, in _get_state
    self.state = lookup[rc].get('status')
KeyError: 403

from running journctl | grep target on the second machine I get this.........

Dec 11 13:25:54 cephrgw02.wl.internal rbd-target-api[1462]: Checking for config object changes every 1s
Dec 11 13:25:54 cephrgw02.wl.internal rbd-target-api[1462]:  * Running on http://0.0.0.0:5000/
Dec 11 13:25:55 cephrgw02.wl.internal rbd-target-gw[1459]: No OSD blacklist entries found
Dec 11 13:25:55 cephrgw02.wl.internal rbd-target-gw[1459]: Reading the configuration object to update local LIO configuration
Dec 11 13:25:55 cephrgw02.wl.internal rbd-target-gw[1459]: Configuration does not have an entry for this host(cephrgw02) - nothing to define to LIO
Dec 11 13:26:05 cephrgw02.wl.internal rbd-target-api[1462]: 10.2.51.41 - - [11/Dec/2017 13:26:05] "GET /api/_ping HTTP/1.1" 200 -
Dec 11 13:26:05 cephrgw02.wl.internal rbd-target-api[1462]: 10.2.51.41 - - [11/Dec/2017 13:26:05] "GET /api/_ping HTTP/1.1" 200 -
Dec 11 13:26:05 cephrgw02.wl.internal rbd-target-api[1462]: 10.2.51.41 - - [11/Dec/2017 13:26:05] "GET /api/_ping HTTP/1.1" 200 -
Dec 11 13:26:05 cephrgw02.wl.internal rbd-target-api[1462]: 10.2.51.41 - - [11/Dec/2017 13:26:05] "GET /api/_ping HTTP/1.1" 200 -
Dec 11 13:26:05 cephrgw02.wl.internal rbd-target-api[1462]: 10.2.51.41 - - [11/Dec/2017 13:26:05] "GET /api/_ping HTTP/1.1" 200 -
Dec 11 13:26:05 cephrgw02.wl.internal rbd-target-api[1462]: 10.2.51.41 - - [11/Dec/2017 13:26:05] "GET /api/_ping HTTP/1.1" 200 -
Dec 11 13:27:46 cephrgw02.wl.internal rbd-target-api[1462]: Change detected - internal 3 / xattr 4 refreshing
Dec 11 13:32:10 cephrgw02.wl.internal rbd-target-api[1462]: 10.2.41.41 - - [11/Dec/2017 13:32:10] "GET /api/_ping HTTP/1.1" 403 -
Dec 11 14:44:53 cephrgw02.wl.internal rbd-target-api[1462]: 10.2.41.41 - - [11/Dec/2017 14:44:53] "GET /api/_ping HTTP/1.1" 403 -
Dec 11 14:44:53 cephrgw02.wl.internal rbd-target-api[1462]: 10.2.41.41 - - [11/Dec/2017 14:44:53] "GET /api/_ping HTTP/1.1" 403 -
Dec 11 14:53:58 cephrgw02.wl.internal rbd-target-api[1462]: 127.0.0.1 - - [11/Dec/2017 14:53:58] "GET /api/config HTTP/1.1" 200 -
Dec 11 14:54:07 cephrgw02.wl.internal rbd-target-api[1462]: 127.0.0.1 - - [11/Dec/2017 14:54:07] "GET /api/config HTTP/1.1" 200 -
Dec 11 14:54:17 cephrgw02.wl.internal rbd-target-api[1462]: 127.0.0.1 - - [11/Dec/2017 14:54:17] "GET /api/config HTTP/1.1" 200 -
Dec 11 14:54:39 cephrgw02.wl.internal rbd-target-api[1462]: 127.0.0.1 - - [11/Dec/2017 14:54:39] "GET /api/config HTTP/1.1" 200 -
Dec 11 15:49:30 cephrgw02.wl.internal rbd-target-api[1462]: 127.0.0.1 - - [11/Dec/2017 15:49:30] "GET /api/config HTTP/1.1" 200 -
Dec 11 15:49:38 cephrgw02.wl.internal rbd-target-api[1462]: 127.0.0.1 - - [11/Dec/2017 15:49:38] "GET /api/config HTTP/1.1" 200 -

All the sites on 10.2.41.41 get 403 errors while the rest get 200 returns

From the first server when I run journalctl | grep target I get this....

Dec 11 14:45:05 cephrgw01.wl.internal rbd-target-api[1498]: Gateway request received, with validity checks disabled
Dec 11 14:45:05 cephrgw01.wl.internal rbd-target-api[1498]: 10.2.41.41 - - [11/Dec/2017 14:45:05] "GET /api/_ping HTTP/1.1" 403 -
Dec 11 14:45:05 cephrgw01.wl.internal rbd-target-api[1498]: 127.0.0.1 - - [11/Dec/2017 14:45:05] "PUT /api/gateway/cephrgw02 HTTP/1.1" 503 -
Dec 11 14:45:06 cephrgw01.wl.internal rbd-target-api[1498]: 10.2.51.41 - - [11/Dec/2017 14:45:06] "GET /api/_ping HTTP/1.1" 200 -
Dec 11 14:45:16 cephrgw01.wl.internal rbd-target-api[1498]: 10.2.51.41 - - [11/Dec/2017 14:45:16] "GET /api/_ping HTTP/1.1" 200 -
Dec 11 14:45:26 cephrgw01.wl.internal rbd-target-api[1498]: 10.2.51.41 - - [11/Dec/2017 14:45:26] "GET /api/_ping HTTP/1.1" 200 -
Dec 11 14:45:36 cephrgw01.wl.internal rbd-target-api[1498]: 10.2.51.41 - - [11/Dec/2017 14:45:36] "GET /api/_ping HTTP/1.1" 200 -
Dec 11 14:45:46 cephrgw01.wl.internal rbd-target-api[1498]: 10.2.51.41 - - [11/Dec/2017 14:45:46] "GET /api/_ping HTTP/1.1" 200 -
Dec 11 14:45:56 cephrgw01.wl.internal rbd-target-api[1498]: 10.2.51.41 - - [11/Dec/2017 14:45:56] "GET /api/_ping HTTP/1.1" 200 -
Dec 11 14:46:06 cephrgw01.wl.internal rbd-target-api[1498]: 10.2.51.41 - - [11/Dec/2017 14:46:06] "GET /api/_ping HTTP/1.1" 200 -
Dec 11 14:46:16 cephrgw01.wl.internal rbd-target-api[1498]: 10.2.51.41 - - [11/Dec/2017 14:46:16] "GET /api/_ping HTTP/1.1" 200 -
Dec 11 14:46:26 cephrgw01.wl.internal rbd-target-api[1498]: 10.2.51.41 - - [11/Dec/2017 14:46:26] "GET /api/_ping HTTP/1.1" 200 -
Dec 11 14:54:11 cephrgw01.wl.internal rbd-target-api[1498]: 10.2.51.43 - - [11/Dec/2017 14:54:11] "GET /api/_ping HTTP/1.1" 403 -
Dec 11 14:54:19 cephrgw01.wl.internal rbd-target-api[1498]: 10.2.51.43 - - [11/Dec/2017 14:54:19] "GET /api/_ping HTTP/1.1" 403 -
Dec 11 14:54:30 cephrgw01.wl.internal rbd-target-api[1498]: 10.2.51.43 - - [11/Dec/2017 14:54:30] "GET /api/_ping HTTP/1.1" 403 -
Dec 11 14:54:51 cephrgw01.wl.internal rbd-target-api[1498]: 10.2.51.43 - - [11/Dec/2017 14:54:51] "GET /api/_ping HTTP/1.1" 403 -
Dec 11 15:49:42 cephrgw01.wl.internal rbd-target-api[1498]: 10.2.51.43 - - [11/Dec/2017 15:49:42] "GET /api/_ping HTTP/1.1" 403 -
Dec 11 15:49:51 cephrgw01.wl.internal rbd-target-api[1498]: 10.2.51.43 - - [11/Dec/2017 15:49:51] "GET /api/_ping HTTP/1.1" 403 -

**Comment by pcuzner** [comment]
The IP addresses given to the gateways are the same ones used to create the iscsi portals. So I suspect you should have created the gateways using the 10.2.41.x ip address. The next thing is the status issue. After you deployed I'm assuming you have the rbd-target-gw and rbd-target-api daemons running on each gateway. rbd-target-api listens on port 500x(check with systemctl status) - so is this port open? An UNKNOWN state implies a connection problem, but the 403 suggests that there is potentially a mismatch between the api servers. Are they using the same mode http or https, if https are the ssl certs the same on each gateway?

**Comment by squarejester** [comment]
First of all, Thank you very much for helping. I really appreciate it.

Sorry about the confusion about the gateway addresses. Yes, I did actually create the original cephrgw01 on 10.2.41.41, no on the 10.2.51.41 address as I put in the post. I also did try to create the gateway using the 10.2.41.43 address for ceprgw02 but got the same results. 

Also forgot to mention that firewalld is completely disabled and shut down on all ceph nodes for now and have always been. Both servers are identical and use http, https has not been setup. 

rbd-target-gw and rdb-taget-api are running on both machines as shown by systemctl status.

First server ....

State: running
     Jobs: 0 queued
   Failed: 0 units
    Since: Mon 2017-12-11 12:38:17 HST; 5h 0min ago
   CGroup: /
           tq1 /usr/lib/systemd/systemd --switched-root --system --deserialize 21
           tquser.slice
           x mquser-0.slice
           x   mqsession-8.scope
           x     tq3318 sshd: root@pts/0
           x     tq3323 -bash
           x     tq3392 systemctl status
           x     mq3393 less
           mqsystem.slice
             tqrbd-target-api.service
             x mq1498 /usr/bin/python /usr/bin/rbd-target-api
             tqrbd-target-gw.service
             x mq1494 /usr/bin/python2 -u /usr/bin/rbd-target-gw
             tqtuned.service
             x mq1424 /usr/bin/python -Es /usr/sbin/tuned -l -P
             tqtcmu-runner.service
             x mq1423 /usr/bin/tcmu-runner
             tqpostfix.service
             x tq1753 /usr/libexec/postfix/master -w
             x tq1755 qmgr -l -t unix -u
             x mq3391 pickup -l -t unix -u
             tqsshd.service
             x mq1416 /usr/sbin/sshd -D
             tqcrond.service
             x mq1084 /usr/sbin/crond -n
             tqNetworkManager.service
             x mq1075 /usr/sbin/NetworkManager --no-daemon
             tqdbus.service
             x mq1061 /bin/dbus-daemon --system --address=systemd: --nofork --nopidfile --systemd-activation
             tqrsyslog.service
             x mq1059 /usr/sbin/rsyslogd -n
             tqchronyd.service
             x mq1074 /usr/sbin/chronyd
             tqirqbalance.service
             x mq1053 /usr/sbin/irqbalance --foreground
             tqpolkit.service
             x mq1052 /usr/lib/polkit-1/polkitd --no-debug
             tqsystemd-logind.service
             x mq1050 /usr/lib/systemd/systemd-logind
             tqauditd.service
             x mq1026 /sbin/auditd
             tqsystemd-udevd.service
             x mq788 /usr/lib/systemd/systemd-udevd
             tqlvm2-lvmetad.service
             x mq775 /usr/sbin/lvmetad -f
             tqsystem-ceph\x2dradosgw.slice
             x mqceph-radosgw@rgw.cephrgw01.service
             x   mq1421 /usr/bin/radosgw -f --cluster ceph --name client.rgw.cephrgw01 --setuser ceph --setgroup
             tqsystem-getty.slice
             x mqgetty@tty1.service
             x   mq1103 /sbin/agetty --noclear tty1 linux
             mqsystemd-journald.service
               mq759 /usr/lib/systemd/systemd-journal


Second server.....

 State: running
     Jobs: 0 queued
   Failed: 0 units
    Since: Mon 2017-12-11 13:25:18 HST; 4h 15min ago
   CGroup: /
           tq1 /usr/lib/systemd/systemd --switched-root --system --deserialize 21
           tquser.slice
           x mquser-0.slice
           x   mqsession-6.scope
           x     tq2524 sshd: root@pts/0
           x     tq2528 -bash
           x     tq2543 systemctl status
           x     mq2544 less
           mqsystem.slice
             tqrbd-target-api.service
             x mq1462 /usr/bin/python /usr/bin/rbd-target-api
             tqrbd-target-gw.service
             x mq1459 /usr/bin/python2 -u /usr/bin/rbd-target-gw
             tqtuned.service
             x mq1394 /usr/bin/python -Es /usr/sbin/tuned -l -P
             tqpostfix.service
             x tq1722 /usr/libexec/postfix/master -w
             x tq1724 qmgr -l -t unix -u
             x mq2506 pickup -l -t unix -u
             tqsshd.service
             x mq1389 /usr/sbin/sshd -D
             tqtcmu-runner.service
             x mq1387 /usr/bin/tcmu-runner
             tqcrond.service
             x mq1069 /usr/sbin/crond -n
             tqrsyslog.service
             x mq1064 /usr/sbin/rsyslogd -n
             tqpolkit.service
             x mq1063 /usr/lib/polkit-1/polkitd --no-debug
             tqsystemd-logind.service
             x mq1062 /usr/lib/systemd/systemd-logind
             tqNetworkManager.service
             x mq1060 /usr/sbin/NetworkManager --no-daemon
             tqdbus.service
             x mq1050 /bin/dbus-daemon --system --address=systemd: --nofork --nopidfile --systemd-activation
             tqirqbalance.service
             x mq1048 /usr/sbin/irqbalance --foreground
             tqauditd.service
             x mq1023 /sbin/auditd
             tqsystemd-udevd.service
             x mq785 /usr/lib/systemd/systemd-udevd
             tqlvm2-lvmetad.service
             x mq780 /usr/sbin/lvmetad -f
             tqsystem-ceph\x2dradosgw.slice
             x mqceph-radosgw@rgw.cephrgw02.service
             x   mq1388 /usr/bin/radosgw -f --cluster ceph --name client.rgw.cephrgw02 --setuser ceph --setgroup
             tqsystem-getty.slice
             x mqgetty@tty1.service
             x   mq1093 /sbin/agetty --noclear tty1 linux
             mqsystemd-journald.service
               mq752 /usr/lib/systemd/systemd-journald

However.....when i try to telnet to port 500 on 10.2.41.41 or 10.2.41.43 (from each of the servers to themselves or to each other) I get a connection refused. I installed net-tools and ran netstat -a to see the results and saw nothing for port 500 on either machine. I also used curl 10.2.41.41:500 and curl 10.2.41.43:500 and both came back refused. cephrgw01 is showing that its listening for iscsi port. cephrgw02 is not. Another bit of information is that these machines are using host files that are all identical and have cephrgw01 at 10.2.51.41 and cephrgw02 at 10.2.51.43

Maybe I'm missing something and its there or genuinely not there, I don't know how to definitely test an api connection as I am not a developer. It seems like both services are up and running on both machines according to systemctl status but I don't see port 500.

Any suggestions?

**Comment by squarejester** [comment]
FYI, looking at the original post I noticed it said it was running the api on port 5000 so I did a curl to both servers on port 5000 and got responses...here is what I got.....I'm guessing this means the api is reachable but for some reason getting a 403 error.

[root@cephrgw01 ~]# curl 10.2.41.43:5000
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>404 Not Found</title>
<h1>Not Found</h1>
<p>The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.</p>
[root@cephrgw01 ~]# curl 10.2.41.41:5000
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>404 Not Found</title>
<h1>Not Found</h1>
<p>The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.</p>
[root@cephrgw01 ~]#

**Comment by pcuzner** [comment]
Sorry if my comment confused you. It's not port 500, it's 500x i.e. 5000 or 5001 normally. If you look at systemctl status rbd-target-api it will tell you the port it's using and whether it's running in https mode among other things.

**Comment by squarejester** [comment]
Server one  - cephrgw01

[root@cephrgw01 ~]# systemctl status rbd-target-gw
? rbd-target-gw.service - Setup system to export rbd images through LIO
   Loaded: loaded (/usr/lib/systemd/system/rbd-target-gw.service; enabled; vendor preset: disabled)
   Active: active (running) since Mon 2017-12-11 12:38:28 HST; 5h 48min ago
 Main PID: 1494 (rbd-target-gw)
   CGroup: /system.slice/rbd-target-gw.service
           mq1494 /usr/bin/python2 -u /usr/bin/rbd-target-gw

Dec 11 12:38:53 cephrgw01.wl.internal rbd-target-gw[1494]: No OSD blacklist entries found
Dec 11 12:38:53 cephrgw01.wl.internal rbd-target-gw[1494]: Reading the configuration object to update local LIO configuration
Dec 11 12:38:53 cephrgw01.wl.internal rbd-target-gw[1494]: Processing Gateway configuration
Dec 11 12:38:53 cephrgw01.wl.internal rbd-target-gw[1494]: (Gateway.create_tpg) created TPG '1' for target iqn 'iqn.2003-01.com.redhat.iscsi-gw:test'
Dec 11 12:38:53 cephrgw01.wl.internal rbd-target-gw[1494]: (Gateway.create_target) created an iscsi target with iqn of 'iqn.2003-01.com.redhat.iscsi-gw:test'
Dec 11 12:38:53 cephrgw01.wl.internal rbd-target-gw[1494]: Processing LUN configuration
Dec 11 12:38:53 cephrgw01.wl.internal rbd-target-gw[1494]: No LUNs to export
Dec 11 12:38:53 cephrgw01.wl.internal rbd-target-gw[1494]: Processing client configuration
Dec 11 12:38:53 cephrgw01.wl.internal rbd-target-gw[1494]: Adding the IP to the enabled tpg, allowing iSCSI logins
Dec 11 12:38:53 cephrgw01.wl.internal rbd-target-gw[1494]: iSCSI configuration load complete
[root@cephrgw01 ~]# systemctl status rbd-target-api
? rbd-target-api.service - Ceph iscsi target configuration API
   Loaded: loaded (/usr/lib/systemd/system/rbd-target-api.service; enabled; vendor preset: disabled)
   Active: active (running) since Mon 2017-12-11 12:38:28 HST; 5h 48min ago
 Main PID: 1498 (rbd-target-api)
   CGroup: /system.slice/rbd-target-api.service
           mq1498 /usr/bin/python /usr/bin/rbd-target-api

Dec 11 14:46:16 cephrgw01.wl.internal rbd-target-api[1498]: 10.2.51.41 - - [11/Dec/2017 14:46:16] "GET /api/_ping HTTP/1.1" 200 -
Dec 11 14:46:26 cephrgw01.wl.internal rbd-target-api[1498]: 10.2.51.41 - - [11/Dec/2017 14:46:26] "GET /api/_ping HTTP/1.1" 200 -
Dec 11 14:54:11 cephrgw01.wl.internal rbd-target-api[1498]: 10.2.51.43 - - [11/Dec/2017 14:54:11] "GET /api/_ping HTTP/1.1" 403 -
Dec 11 14:54:19 cephrgw01.wl.internal rbd-target-api[1498]: 10.2.51.43 - - [11/Dec/2017 14:54:19] "GET /api/_ping HTTP/1.1" 403 -
Dec 11 14:54:30 cephrgw01.wl.internal rbd-target-api[1498]: 10.2.51.43 - - [11/Dec/2017 14:54:30] "GET /api/_ping HTTP/1.1" 403 -
Dec 11 14:54:51 cephrgw01.wl.internal rbd-target-api[1498]: 10.2.51.43 - - [11/Dec/2017 14:54:51] "GET /api/_ping HTTP/1.1" 403 -
Dec 11 15:49:42 cephrgw01.wl.internal rbd-target-api[1498]: 10.2.51.43 - - [11/Dec/2017 15:49:42] "GET /api/_ping HTTP/1.1" 403 -
Dec 11 15:49:51 cephrgw01.wl.internal rbd-target-api[1498]: 10.2.51.43 - - [11/Dec/2017 15:49:51] "GET /api/_ping HTTP/1.1" 403 -
Dec 11 18:19:49 cephrgw01.wl.internal rbd-target-api[1498]: 10.2.41.41 - - [11/Dec/2017 18:19:49] "GET / HTTP/1.1" 404 -
Dec 11 18:20:18 cephrgw01.wl.internal rbd-target-api[1498]: 10.2.41.41 - - [11/Dec/2017 18:20:18] "GET / HTTP/1.1" 404 -
[root@cephrgw01 ~]#


Server two cephrgw02

[root@cephrgw02 ~]# systemctl status rbd-target-api
? rbd-target-api.service - Ceph iscsi target configuration API
   Loaded: loaded (/usr/lib/systemd/system/rbd-target-api.service; enabled; vendor preset: disabled)
   Active: active (running) since Mon 2017-12-11 13:25:29 HST; 5h 1min ago
 Main PID: 1462 (rbd-target-api)
   CGroup: /system.slice/rbd-target-api.service
           mq1462 /usr/bin/python /usr/bin/rbd-target-api

Dec 11 14:44:53 cephrgw02.wl.internal rbd-target-api[1462]: 10.2.41.41 - - [11/Dec/2017 14:44:53] "GET /api/_ping HTTP/1.1" 403 -
Dec 11 14:44:53 cephrgw02.wl.internal rbd-target-api[1462]: 10.2.41.41 - - [11/Dec/2017 14:44:53] "GET /api/_ping HTTP/1.1" 403 -
Dec 11 14:53:58 cephrgw02.wl.internal rbd-target-api[1462]: 127.0.0.1 - - [11/Dec/2017 14:53:58] "GET /api/config HTTP/1.1" 200 -
Dec 11 14:54:07 cephrgw02.wl.internal rbd-target-api[1462]: 127.0.0.1 - - [11/Dec/2017 14:54:07] "GET /api/config HTTP/1.1" 200 -
Dec 11 14:54:17 cephrgw02.wl.internal rbd-target-api[1462]: 127.0.0.1 - - [11/Dec/2017 14:54:17] "GET /api/config HTTP/1.1" 200 -
Dec 11 14:54:39 cephrgw02.wl.internal rbd-target-api[1462]: 127.0.0.1 - - [11/Dec/2017 14:54:39] "GET /api/config HTTP/1.1" 200 -
Dec 11 15:49:30 cephrgw02.wl.internal rbd-target-api[1462]: 127.0.0.1 - - [11/Dec/2017 15:49:30] "GET /api/config HTTP/1.1" 200 -
Dec 11 15:49:38 cephrgw02.wl.internal rbd-target-api[1462]: 127.0.0.1 - - [11/Dec/2017 15:49:38] "GET /api/config HTTP/1.1" 200 -
Dec 11 18:19:53 cephrgw02.wl.internal rbd-target-api[1462]: 10.2.41.41 - - [11/Dec/2017 18:19:53] "GET / HTTP/1.1" 404 -
Dec 11 18:20:00 cephrgw02.wl.internal rbd-target-api[1462]: 10.2.41.41 - - [11/Dec/2017 18:20:00] "GET / HTTP/1.1" 404 -
[root@cephrgw02 ~]# systemctl status rbd-target-gw
? rbd-target-gw.service - Setup system to export rbd images through LIO
   Loaded: loaded (/usr/lib/systemd/system/rbd-target-gw.service; enabled; vendor preset: disabled)
   Active: active (running) since Mon 2017-12-11 13:25:29 HST; 5h 1min ago
 Main PID: 1459 (rbd-target-gw)
   CGroup: /system.slice/rbd-target-gw.service
           mq1459 /usr/bin/python2 -u /usr/bin/rbd-target-gw

Dec 11 13:25:29 cephrgw02.wl.internal systemd[1]: Started Setup system to export rbd images through LIO.
Dec 11 13:25:29 cephrgw02.wl.internal systemd[1]: Starting Setup system to export rbd images through LIO...
Dec 11 13:25:54 cephrgw02.wl.internal rbd-target-gw[1459]: Processing osd blacklist entries for this node
Dec 11 13:25:55 cephrgw02.wl.internal rbd-target-gw[1459]: No OSD blacklist entries found
Dec 11 13:25:55 cephrgw02.wl.internal rbd-target-gw[1459]: Reading the configuration object to update local LIO configuration
Dec 11 13:25:55 cephrgw02.wl.internal rbd-target-gw[1459]: Configuration does not have an entry for this host(cephrgw02) - nothing to define to LIO
[root@cephrgw02 ~]#

**Comment by pcuzner** [comment]
OK so cephrgw01/2 IP addresses may be not be correct in the config object. You can confirm by looking directly (rados -p rbd get gateway.conf - | less)

When a gateway is created it registers the IP you gave as the IP address to use for the iscsi portal and also the control path for the api server to talk over. It uses these IP's in the config object as a whitelist, if an API access attempt is made from an unknown IP you get a 403 forbidden

If this is the case, you can take the gateways down, update the config object and bring the gateways back up.

**Comment by squarejester** [comment]
It only shows the first server. I think it is only showing the first server for exactly the reason I started this post in the first place in that **I can't add the second gateway server.** 

I ran the command and got this.....

{
    "clients": {},
    "created": "2017/12/08 22:58:47",
    "disks": {},
    "epoch": 4,
    "gateways": {
        "cephrgw01": {
            "active_luns": 0,
            "created": "2017/12/08 23:10:02",
            "gateway_ip_list": [
                "10.2.41.41"
            ],
            "inactive_portal_ips": [],
            "iqn": "iqn.2003-01.com.redhat.iscsi-gw:test",
            "portal_ip_address": "10.2.41.41",
            "tpgs": 1,
            "updated": "2017/12/08 23:10:02"
        },
        "created": "2017/12/08 23:01:15",
        "ip_list": [
            "10.2.41.41"
        ],
        "iqn": "iqn.2003-01.com.redhat.iscsi-gw:test"
    },
    "groups": {},
    "updated": "2017/12/11 23:27:59",
    "version": 3
}

So I'm a little confused. Should I modify this file instead of trying to add it via GWCLI? If so, how?

**Comment by pcuzner** [comment]
No you don't normally want to interact directly with this file at all. To recap can you attach the output of gwcli -d ls 

Then can you confirm that the rbd-target-gw and rbd-target-api is started on the 2nd gateway server, and you can at least run a curl to the http://10.2.41.x:5000/api ip of the 2nd gateway from the 1st gateway.

When you traceroute from the first gateway to the 2nd gateway's iscsi ip address it's using the 10.2.41 network right?

**Comment by squarejester** [comment]
**UPDATE**

From inside the first server using gwcli i went to the iscsi-target folder location by doing
cd iscsi-target
/iscsi-target>

I then cleared the iscsi config by issuing the clearconfig confirm=true command

/iscsi-target>clearconfig confirm=true

This removed the iqn target and it also removed the existing cephrgw01 gateway

After this I AM ABLE to launch gwcli in BOTH servers.....however;

I then create an iscsi iqn target and verifiy it shows up in both servers (which it does).

Now the issue seems to be that once I create the first gateway (which it forces me to make the local server the first gateway I create) from EITHER server I then cannot create the second gateway. Instead, I get this error...

/iscsi-target...:new/gateways> create skipchecks=true cephrgw02 10.2.41.43
OS version/package checks have been bypassed
Adding gateway, sync'ing 0 disk(s) and 0 client(s)
ok
/iscsi-target...:new/gateways> create skipchecks=true cephrgw01 10.2.41.41
OS version/package checks have been bypassed
Adding gateway, sync'ing 0 disk(s) and 0 client(s)
Failed : Gateway creation failed, gateway(s) unavailable:10.2.41.43(UNKNOWN state),10.2.41.41(UNKNOWN state)

Subsequently when I try to run gwcli from the server that I did NOT create the gateway from, it now gives me the infamous **KeyError: 403**

and 

[root@cephrgw01 ~]# gwcli -d
Adding ceph cluster 'ceph' to the UI
Fetching ceph osd information
Querying ceph for state information
Refreshing disk information from the config object
Refreshing gateway & client information
- checking iSCSI/API ports on cephrgw02
Traceback (most recent call last):
  File "/usr/bin/gwcli", line 187, in <module>
    main()
  File "/usr/bin/gwcli", line 99, in main
    root_node.refresh()
  File "/usr/lib/python2.7/site-packages/gwcli/gateway.py", line 78, in refresh
    self.target.refresh()
  File "/usr/lib/python2.7/site-packages/gwcli/gateway.py", line 341, in refresh
    tgt.gateway_group.load(self.gateway_group)
  File "/usr/lib/python2.7/site-packages/gwcli/gateway.py", line 406, in load
    Gateway(self, gateway_name, gateway_group[gateway_name])
  File "/usr/lib/python2.7/site-packages/gwcli/gateway.py", line 604, in __init__
    self.refresh()
  File "/usr/lib/python2.7/site-packages/gwcli/gateway.py", line 620, in refresh
    self._get_state()
  File "/usr/lib/python2.7/site-packages/gwcli/gateway.py", line 649, in _get_state
    self.state = lookup[rc].get('status')
KeyError: 403

If I run clearconfig again and start over from the other server everything is identical except it won't let me add a second gateway from the other server and I can't launch gwcli from that second server (once the first gateway is created).

Seems connectivity is not an issue here but something either in the code or permissions or something....

Any ideas?

**Comment by squarejester** [comment]
OK. Found the problem and as always its the simple things in life.....

in /etc/ceph/iscsi-gateway.cfg

needed to add

trusted_ip_list =10.2.41.41,10.2.41.43

This solved the problem of adding gateways because as per the gwcli man page api connections are only allowed locally unless you add them to this trusted_ip_list.

Also discovered that the reason the other server is giving me a KeyError:403 is that it only allows you to use gwcli from whichever is the current iscsi HA active server once any gateway server is created. Before creating a gateway (hence no active/passive iscsi AULA in effect) you can run gwcli from both servers.

I proved this by rebooting the active server, waiting for it to come back up and then trying again on the now (newly appointed) active server. Makes sense. Most things in HA environments work as such with their consoles.

There should be something added to the ouput of gwlic from non HA active gateways servers to tell you this instead of a generic Keyerror:403 message that you get so that you know you need to go to the active server to run gwcli.

Now I've moved on to the issue of:

/disks> create pool=vmstorage image=vms size=200g
Failed : disk create/update failed on cephrgw02. LUN allocation failure

which I see in another post is something that needs to be fixed in a kernel patch that is coming.

In the meantime I am going to try using the repository that gelato mentions in the OS not supported thread:

https://shaman.ceph.com/repos/ceph-iscsi-config/master/
https://shaman.ceph.com/repos/ceph-iscsi-cli/master/

and rebuild the servers from scratch. Maybe the fixes for the kernels are there.

**Comment by mikechristie** [comment]
> and rebuild the servers from scratch. Maybe the fixes for the kernels are there.

You should wait a couple of days. There is no updated kernel there yet. I am almost done with a kernel and updated docs and runner packages.

**Comment by squarejester** [comment]
OK. I just updated the kernels on both the gateway servers before I went ahead like crazy to see if it was working now. That was before I saw your last message. 

I installed the latest I could find which brought me up to kernel-4.15.0_rc2_ceph_g040d786032bf-1.x86_64.rpm but of course no luck, still got the same error (probably as expected).

from repo

https://3.chacra.ceph.com/r/kernel/master/040d786032bf59002d374b86d75b04d97624005c/centos/7/flavors/default/x86_64/

Please let me know when the kernel is updated as soon as possible. I plan on updating my entire cluster (no worries not production yet) and look forward to actually being able to mount the storage via iSCSI. That's the entire point right now.
