### ISSUE TITLE
vmware multipath restored issue

### ISSUE THREAD

**Issue by vatelzh** [ceph/ceph-iscsi-cli#60]
I'm testing this scenario:
prerequisite:
    1. create a target and two gateways
    2. create a host and a disk, and map the disk to host.
test steps:
1. discovery the target and login, check the target has one device and two paths.
2. stop one path(stop rbd-target-api/gw and tcmu-runner), and refresh the iscsi adapter in vsphere client.
3. when the path turns to failed, start the services(tcmu-runner, rbd-target-gw/api), check the gateway is ok using gwcli
4. waiting for the path back to normal.

The path can not back to normal even I refresh or rescan, unless I remove this target and discovery it again.

**Comment by vatelzh** [comment]
I clicked rescan, after that, I ran this command, esxcli iscsi session list hangup :( I have to hard  reboot the ESXi host. I will try to reproduce this issue later.

**Comment by vatelzh** [comment]
@mikechristie 

I use linux to reproduce this issue without multipath. 

iscsiadm -m discovery -t st -p 192.168.56.42:3260
192.168.56.43:3260,1 iqn.1998-01.com.vmware:target
192.168.56.42:3260,3 iqn.1998-01.com.vmware:target
[root@node1 wentaozh]# iscsiadm -m node -T iqn.1998-01.com.vmware:target -p 192.168.56.42:3260 --login
Logging in to [iface: default, target: iqn.1998-01.com.vmware:target, portal: 192.168.56.42,3260] (multiple)
iscsiadm: Could not login to [iface: default, target:iqn.1998-01.com.vmware:target, portal: 192.168.56.42,3260].
**iscsiadm: initiator reported error (24 - iSCSI login failed due to authorization failure)**
iscsiadm: Could not log into all portals
[root@node1 wentaozh]# iscsiadm -m node -T iqn.1998-01.com.vmware:target -p 192.168.56.43:3260 --login
Logging in to [iface: default, target: iqn.1998-01.com.vmware:target, portal: 192.168.56.43,3260] (multiple)
Login to [iface: default, target: iqn.1998-01.com.vmware:target, portal: 192.168.56.43,3260] successful.

Reproduce steps:
1. create host iqn.1998-01.com.vmware.sn1 
2. create disk rbd.disk1
3. echo "InitiatorName=iqn.1998-01.com.vmware.sn1" > /etc/iscsi/initiatorname.iscsi
4. discovery and login using portal 192.168.56.42,3260/192.168.56.43,3260, this step is successful.
5. stop one iscsi gateway 192.168.56.42.  systemctl stop rbd-target-api/rbd-target-gw/tcmu-runner, and shutdown the machine.
6. start another machine, and config it's ip to 192.168.56.42,  start tcmu-runner/rbd-target-api 
7. do the step 4, and logon to 192.168.56.42,3260 is failed

/var/log/message, Found this message
**conn 0 login rejected: initiator failed authorization with target**

This can not be reproduced every time :(

**Comment by mikechristie** [comment]
@vatelzh 

Did you add a comment? I got a email, but do not see it.

For the linux reproducer case, when you hit the bug could you send the kernel messages for the iscsi gw/target box? It should be /var/log/messages or wherever you have jouralctl putting it. We can check why the CHAP did not get setup and what error the target is reporting (wrong chap info info vs chap not setup but initiator requesting it, etc).

**Comment by vatelzh** [comment]
@mikechristie Yes, I thought I find another similar issue in Linux.
reproduce key steps:
1. shutdown node 192.168.56.42
2. start a new node, and config it's ip with 192.168.56.42   ---> actually, iscsi-gateway in old node is not stopped yet(I don't know why, maybe rbd-target-gw was stopped very slowly)
3. start iscsi-gateway   ---> new iscsi-gateway is notified that itself was the third iscsi-gateway. Use targetcli to check, and there's no chap info under it's tpgs.  Restart rbd-target-gw would solve this issue.

I don't think this is a problem, so I undo the comment.

**Comment by vatelzh** [comment]
@mikechristie Yes, I thought I find another similar issue in Linux.
reproduce key steps:
1. shutdown node 192.168.56.42
2. start a new node, and config it's ip with 192.168.56.42   ---> actually, iscsi-gateway in old node is not stopped yet(I don't know why, maybe rbd-target-gw was stopped very slowly)
3. start iscsi-gateway   ---> new iscsi-gateway is notified that itself was the third iscsi-gateway. Use targetcli to check, and there's no chap info under it's tpgs.  Restart rbd-target-gw would solve this issue.

I don't think this is a problem, so I undo the comment.

**Comment by vatelzh** [comment]
@mikechristie 

Similar issue again...
reproduce steps:
1. create host-group and hosts and disks, and add them to group
2. login from vsphere, two esxi hosts
3. restart gateway2
4. rescan the target

targetcli ls command output:
On gateway1 node:
  |     | o- iqn.1998-03.com.vmware.sn1 ...................................... [1-way auth, Mapped LUNs: 2]
  |     | | o- mapped_lun0 .............................................. [lun51 user/rbd.disk1 (rw)]
  |     | | o- mapped_lun1 ........................................... [lun52 user/rbd.disk2 (rw)]
  |     | o- iqn.1998-03.com.vmware.sn2 ...................................... [1-way auth, Mapped LUNs: 2]
  |     | | o- mapped_lun0 .............................................. [lun51 user/rbd.disk1 (rw)]
  |     | | o- mapped_lun1 ........................................... [lun52 user/rbd.disk2 (rw)

On gateway2 node:
  |   | | o- iqn.1998-03.com.vmware.sn1 ...................................... [1-way auth, Mapped LUNs: 0]
  |   | | o- iqn.1998-03.com.vmware.sn2 ...................................... [1-way auth, Mapped LUNs: 0]

gwcli ls command output:
both the two gateways have same output like below:
  o- iqn.1998-03.com.vmware.sn1 ..................................... [LOGGED-IN, Auth: CHAP, Disks: 2(0b)]
  | o- lun 0 .......................................................... [rbd.disk1(), Owner: server2]
  | o- lun 1 ....................................................... [rbd.disk2(), Owner: server2]
  o- iqn.1998-03.com.vmware.sn2 ..................................... [LOGGED-IN, Auth: CHAP, Disks: 2(0b)]
  | o- lun 0 .......................................................... [rbd.disk1(), Owner: server2]
  | o- lun 1 ....................................................... [rbd.disk2(), Owner: server2]

targetcli sessions detail command output:
On gateway1 node:
alias: 	sid: 12 type: Normal session-state: LOGGED_IN
    name: iqn.1998-03.com.vmware.sn2 (NOT AUTHENTICATED)
    mapped-lun: 1 backstore: user/rbd.disk2 mode: rw
    mapped-lun: 0 backstore: user/rbd.disk1 mode: rw
    address: 192.168.0.13 (TCP)  cid: 0 connection-state: LOGGED_IN
alias: 	sid: 10 type: Normal session-state: LOGGED_IN
    name: iqn.1998-03.com.vmware.sn1 (NOT AUTHENTICATED)
    mapped-lun: 1 backstore: user/rbd.disk2 mode: rw
    mapped-lun: 0 backstore: user/rbd.disk1 mode: rw
    address: 192.168.0.12 (TCP)  cid: 0 connection-state: LOGGED_IN

On gateway2 node:
alias: 	sid: 4 type: Normal session-state: LOGGED_IN
    name: iqn.1998-03.com.vmware.sn1 (NOT AUTHENTICATED)
    address: 192.168.0.12 (TCP)  cid: 0 connection-state: LOGGED_IN
alias: 	sid: 5 type: Normal session-state: LOGGED_IN
    name: iqn.1998-03.com.vmware.sn2 (NOT AUTHENTICATED)
    address: 192.168.0.13 (TCP)  cid: 0 connection-state: LOGGED_IN

I restart the tcmu-runner and rbd-target-api/gw, it doesn't work.

**Comment by mikechristie** [comment]
So on gw2 you see mapped luns = 0 after the restart? Runner and/or rbd-target-gw must have failed at some point.

Could you give me the steps you used to restart the gw? Did you reboot the entire machine or restart only specific services?

Could you also give me the /var/log/messages and /var/log/tcmu-runner.log and /var/log/rbd-target-gw.log from gateway 2?

**Comment by vatelzh** [comment]
It's my fault :(
I use ceph-iscsi-config package version 2.3, and I applyed the patch from pcuzner  [https://github.com/ceph/ceph-iscsi-config/pull/33](url) yesterday.  The problem is solved. 

Sorry for wasting your time...

**Comment by vatelzh** [comment]
Closing it.
