### ISSUE TITLE
resize issue

### ISSUE THREAD

**Issue by vatelzh** [ceph/ceph-iscsi-cli#61]
Using gwcli to create rbd.disk1 with 10GB, and I want to resize it to 101GB, so I resize it as below:
/disks resize rbd.disk1 101G

I check the image info with rbd info disk1, and the size is 101GB. 
I check the /sys/kernel/config/target/iscsi/
cat info 
Status: ACTIVATED  Max Queue Depth: 0  SectorSize: 512  HwMaxSectors: 128
        Config: rbd/rbd/disk1;osd_op_timeout=30 Size: 108447924224

The problem is when I using iscsi initiator to login, I find the LUN size is still 10GB.
Is this a bug?

**Comment by mikechristie** [comment]
Resize is broken right now.

On newer kernels it will work, but can cause hangs if the device is blacklisted.

On older kernels you will not see the size updated like above.

If you reboot the gws then the new size would take affect and the initiator would see it when the device is rescanned.

**Comment by vatelzh** [comment]
> On newer kernels it will work, but can cause hangs if the device is blacklisted.

@mikechristie which kernel version works? or which target patch should I apply in kernel?

**Comment by mikechristie** [comment]
@pcuzer, yeah it is probably best to just disable for now.

@vatelzh, there is no fix done yet. For my comment about it working I should have been more specific. If you use the kernel and patches listed in the tcmu-runner 1.3.0rc4 release notes then it would work under really specific conditions. It is not safe to use right now.

**Comment by pcuzner** [comment]
@mikechristie Ok. I have a patch for cli start up times, so once that's confirmed by vatelzh, let's get that merged, and then I'll drop resize out of the cli and api in a subsequent PR.

**Comment by mikechristie** [comment]
@pcuzner  Do not worry about disabling resize. The PRs:

https://github.com/ceph/ceph-iscsi-config/pull/43
https://github.com/ceph/ceph-iscsi-config/pull/27
https://github.com/open-iscsi/tcmu-runner/pull/346

should fix all the known issues except the one where a initiator could race with us. It could be rescanning the size on each path at the same time we are updating and the initiator could end up with a mismatch on different paths. For that race you currently have to initiate manual resize on the initiator side.

**Comment by mikechristie** [comment]
Resize should be working in the current release. Closing this issue.
