### ISSUE TITLE
Hi，I don't not know what API provides.

### ISSUE THREAD

**Issue by letterwuyu** [ceph/ceph-iscsi-cli#75]
I'm trying to manage ceph iscsi gateway  with http，
But do we have a API document？ Is it just to create a gateway？

**Comment by mikechristie** [comment]
There is no API document because there is no supported API yet.

**Comment by letterwuyu** [comment]
Oh, thank you for your answer

**Comment by pcuzner** [comment]
As Mike said, no 'supported/stable' API yet. But the api is used by the cli, so if you want a list of what is currently available you can just hit the /api endpoint once you have rbd-target-api daemon started. eg. curl --insecure --user admin:admin -X GET http://192.168.122.69:5000/api or use your favourite rest api interface......

**Comment by letterwuyu** [comment]
@pcuzner，thinks，Your answer is very helpful to me , I just want to try to control the gateway through Web UI，

**Comment by letterwuyu** [comment]
Hi I verified all the API in the list（ from curl --insecure --user admin:admin -X GET http://192.168.122.69:5000/api ），I find that most of them are available and all gateways are synchronized with api change.But when I used  "curl --insecure --user admin:admin -X PUT http://192.168.122.69:5000/api/target/iqn.2003-01.com.redhat.iscsi-gw0", I made a mistake, It is found that local and other gateways are not effective through gwcli ，the targetcli finds that only the local is effective， so, Is that why Mike says not support API ？

**Comment by mikechristie** [comment]
I think that specific issue was just fixed the other day in this commit:

https://github.com/ceph/ceph-iscsi-cli/commit/8f5066c816d31338b842b84ed6bbbb476f84df36

The general reason we said we do not have a supported API yet, is because the only tool using it is gwcli, and we might have made some mistakes in the design and we also do not want to make the API gwcli specific.

We are open to making a supported API though.

**Comment by letterwuyu** [comment]
Yes, I can successfully create target through the code to create a API and I won't be confused anymore. Thank you for your help
