### ISSUE TITLE
update the Manual Installation Guide

### ISSUE THREAD

**Issue by denggw-cn** [ceph/ceph-iscsi-cli#77]
Hi, everyone:
I deploed the ceph cluster ,and used LIO as iSCSI target tool in few days.Today, I found a issue about deployment tutorial.
I used the manual ways to deploed the ceph cluster, so **I had not a rbd pool named 'rbd'**, result in error when I ware running  'rbd-target-gw'.

Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/bin/rbd-target-gw", line 33, in exception_handler
    clearconfig()
  File "/usr/bin/rbd-target-gw", line 82, in clearconfig
    gw.drop_target(local_gw)
  File "/usr/lib/python2.7/site-packages/ceph_iscsi_config/lio.py", line 58, in drop_target
    if this_host in self.config.config['gateways']:
KeyError: 'gateways'

Original exception was:
Traceback (most recent call last):
  File "/usr/bin/rbd-target-gw", line 462, in <module>
    halt("Unable to open/read the configuration object")
  File "/usr/bin/rbd-target-gw", line 210, in halt
    clearconfig()
  File "/usr/bin/rbd-target-gw", line 82, in clearconfig
    gw.drop_target(local_gw)
  File "/usr/lib/python2.7/site-packages/ceph_iscsi_config/lio.py", line 58, in drop_target
    if this_host in self.config.config['gateways']:
KeyError: 'gateways'

So, I suggest add a tips in deployment tutorial, to **remind user check if they have rbd pool named 'rbd' in their clusters**. Need to update the Manual Installation Guide URL likes:
[https://access.redhat.com/documentation/en-us/red_hat_ceph_storage/2/html/block_device_guide/using_an_iscsi_gateway_technology_preview#configuring_the_iscsi_target_using_the_command_line_interface](https://access.redhat.com/documentation/en-us/red_hat_ceph_storage/2/html/block_device_guide/using_an_iscsi_gateway_technology_preview#configuring_the_iscsi_target_using_the_command_line_interface
)
[http://docs.ceph.com/docs/master/rbd/iscsi-target-cli/](http://docs.ceph.com/docs/master/rbd/iscsi-target-cli/)

Thanks!!

**Comment by mikechristie** [comment]
Thanks. I was just updating the docs here:

https://github.com/ceph/ceph/pull/19931#issuecomment-357976407

Will add a note about this.

Also, it looks like you are using a old version of the RHCS docs. It is for the older RHCS 2.x version. There is a updated here:

https://access.redhat.com/documentation/en-us/red_hat_ceph_storage/3/html/block_device_guide/using_an_iscsi_gateway
