### ISSUE TITLE
How do I create multiple targets?

### ISSUE THREAD

**Issue by junxfl** [ceph/ceph-iscsi-cli#89]
I have 10 gateway node, I want to select three nodes to provide services per target, but now only create one target, all 10 nodes provide services.

**Comment by dillaman** [comment]
Such a use-case isn't currently handled by this tool. The best workaround would be to configure 3 3-node clusters.

**Comment by junxfl** [comment]
Thank you very much.Is there a development plan for this?

**Comment by dillaman** [comment]
It's not on the immediate horizon but I think this could be a nice addition in the future.

**Comment by mikechristie** [comment]
Just linking all these so we can discuss in one place

https://github.com/open-iscsi/tcmu-runner/issues/400
https://github.com/ceph/ceph-iscsi-config/issues/61
